
<!--
<form class="form" id="surveyForm" action="</*?php echo $this->getFormAction();?>" method="post">
    <div>My Form</div>
    <fieldset>
    <div>
        
        <p>
            Rating: 
            <input type="range" min="1" max="5" value="1" class="slider" id="ratingRange">
        </p>
        <p>
            Message:
            <textarea row="2" column="50" id="message"></textarea>
        </p>
    </div>
    <input type="submit" value="submit">
    </fieldset>
</form>
-->
<div>My Form</div>

<?/*php 
    for (var $i = 0; $i < 3; $i ++ ) {
        echo '<div> Product: '. $this->getProductByID($i) . '<br>';
        echo
    }
   
?>

